In [ ]:
#Question 1


In [1]:
#Question 2
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
heart_disease = fetch_ucirepo(id=45) 
  
# data (as pandas dataframes) 
X = heart_disease.data.features 
y = heart_disease.data.targets 
  
# metadata 
print(heart_disease.metadata) 
  
# variable information 
print(heart_disease.variables) 

data_features = pd.DataFrame(heart_disease.data.features, columns=heart_disease.data.feature_names)
data_targets = pd.Series(heart_disease.data.targets.squeeze(), name='Outcome')
columns_to_encode = ['sex','cp','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']
heart_df = pd.get_dummies(data_features[columns_to_encode])
heart_df = heart_df[['sex','cp','chol','fbs','restecg', 'exang','oldpeak','slope','ca']].dropna()
heart_df.head()

{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'ID': 231, 'type': 'NATIVE', 'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M

sex  cp  chol  fbs  restecg  exang  oldpeak  slope   ca
0    1   1   233    1        2      0      2.3      3  0.0
1    1   4   286    0        2      1      1.5      2  3.0
2    1   4   229    0        2      1      2.6      2  2.0
3    1   3   250    0        0      0      3.5      3  0.0
4    0   2   204    0        2      0      1.4      1  0.0

In [2]:
from sklearn.linear_model import LinearRegression
X = np.array(heart_df['sex']).reshape(-1,1)
y = np.array(heart_df['chol']).reshape(-1,1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
regression_model = LinearRegression()
regression_model.fit(X_train, y_train)
y_pred = regression_model.predict(X_test)
y_pred
accuracy_score = regression_model.score(X_test, y_test)
print(accuracy_score)

0.02960914256257763


In [3]:
%pip install imblearn


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: /usr/local/Cellar/jupyterlab/4.2.3/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:

from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)

X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
model = LinearRegression()
model.fit(X_resampled, y_resampled)
y_pred = model.predict(X_test)

In [5]:
y_pred
accuracy_score = model.score(X_test, y_test)
print(accuracy_score)

0.00794201672407513


In [6]:
X = heart_df.drop(['sex'], axis = 1)
y = heart_df['sex']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) 
X_test = sc.fit_transform(X_test)

knn = KNeighborsClassifier(n_neighbors=15) 
knn.fit(X_train, y_train) 

y_pred = knn.predict(X_test)
print(y_pred)
print(type(y_pred))
print(knn.score(X_test, y_test))

[1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0
 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1]
<class 'numpy.ndarray'>
0.7333333333333333


In [7]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)

X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
model = LinearRegression()
model.fit(X_resampled, y_resampled)
y_pred = model.predict(X_test)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_resampled = sc.fit_transform(X_resampled) 
X_test = sc.fit_transform(X_test)

knn = KNeighborsClassifier(n_neighbors=15) 
knn.fit(X_resampled, y_resampled) 

y_pred = knn.predict(X_test)
print(y_pred)
print(type(y_pred))
print(knn.score(X_resampled, y_resampled))

[0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0 1 0 1 0
 0 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0]
<class 'numpy.ndarray'>
0.6347517730496454


In [17]:
%pip install scikit-learn


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: /usr/local/Cellar/jupyterlab/4.2.3/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [18]:
#Question 3
from sklearn import metrics
metrics.roc_curve(y_test, y_pred, pos_label=None, sample_weight=None, drop_intermediate=True)

(array([0.       , 0.4137931, 1.       ]),
 array([0.        , 0.45901639, 1.        ]),
 array([inf,  1.,  0.]))